### ISSUE TITLE
Currency code issue with 477975 and other bins too

### ISSUE THREAD

**Issue by anshulklr** [samymassoud/bintable#2]
According to Visa, the currency is EUR for these BIN. Is it the right assumption and what are your sources?

**Comment by bintable** [comment]
Hello,

The mention information about currency is country-related.
The BIN Block is assigned to the bank, and the bank can issue cards under any supported currency without restriction, so this information is not available to us, possibly could be with Visa as they are the one who is offering the block to the bank.

Thanks.
