### ISSUE TITLE
Issue on Incorrect BIN details

### ISSUE THREAD

**Issue by BarraqDimuthu** [samymassoud/bintable#6]
Dear Team

Please note that the 454887 BIN is owned by **Barraq Finance Company** in Saudi Arabia. Please be kind enough to correct your website details. The entity name mentioned against the said BIN does not exist in Saudi Arabia. 

I have attached the Visa conformation screen for your reference. Once updated please let me know. 
![1](https://github.com/bintable/data/assets/168335412/6f0b419d-6d6a-4504-b95b-01392390b021)
![2](https://github.com/bintable/data/assets/168335412/0a255b66-64a8-45f0-a67a-27488a01e46a)

Thanks
Dimuthu

**Comment by bintable** [comment]
Hello Baraq, Thank you for sharing, this was changed, please le me know if you would require any further help.

Thanks.

**Comment by BarraqDimuthu** [comment]
Dear Team

Noted with thanks

Thanks
Dimuthu
